### ISSUE TITLE
Gripper URDF in self collision under default pose

### ISSUE THREAD

**Issue by wujiashu0421** [agilexrobotics/piper_ros#1]
As per title. 

**Problem:** The origin position of joints 7 & 8 are both located at `xyz="0 0 0.13503"`. Thus, at default pose the gripper's mesh model collides. 

**Solution**: Consider modifying the origin position of joints 7 and 8 to have better clearance between each other

**Comment by RosenYin** [comment]
将初始位置各朝反方向移动了0.0001m
